service: time-sheets-converter
runtime: nodejs18
instance_class: F1
env: standard

automatic_scaling:
  min_instances: 1
  max_instances: 1

handlers:
  - url: /
    static_files: dist/time-sheets-converter/browser/index.html
    upload: dist/time-sheets-converter/browser/index.html

  - url: /(.*\.js)
    static_files: dist/time-sheets-converter/browser/\1
    upload: dist/time-sheets-converter/browser/.*\.js

  - url: /(.*)
    static_files: dist/time-sheets-converter/browser/index.html
    upload: dist/time-sheets-converter/browser/index.html